"""Added test_prop to Groups

Revision ID: 26770f8ac7d8
Revises: 86af03593e2a
Create Date: 2022-08-26 12:07:24.960622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26770f8ac7d8'
down_revision = '86af03593e2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Groups', sa.Column('test_prop', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Groups', 'test_prop')
    # ### end Alembic commands ###
