"""Added blogs table

Revision ID: 86af03593e2a
Revises: ce273fe0537f
Create Date: 2022-08-26 04:36:59.490044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86af03593e2a'
down_revision = 'ce273fe0537f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('about', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Blogs')
    # ### end Alembic commands ###
