services:
  dummy_fast_api:
    build:
      context: .  # Указываем текущую директорию как контекст сборки
      dockerfile: fastapi.Dockerfile # Указываем конкретный Dockerfile
    container_name: dummy_fast_api
    ports:
      - "5002:5002" # Открываем порт 5002 для работы
    volumes:
      - fastapi-my-volume:/app/model-data # Монтируем том в директорию контейнера (замените путь на нужный)
    restart: always # Автоматический перезапуск при сбое

volumes:
  fastapi-my-volume: # Определяем том